Alternative INI file lookup plugin for Ansible
This version of the INI lookup uses ConfigObj instead of ConfigParser,
which confers the ability to read INI files that don't have a defined section
header, thus avoiding the error:
    Error: 'File contains no section headers.'
Otherwise works similarly, see docstring for more info.